### ISSUE TITLE
DATA

### ISSUE THREAD

**Issue by fanzz1208** [laquabe/OneNet#2]
--dataset_name ace2004 \
    --dataset_path datasets/ace2004/listwise_merge.jsonl 
    
    
    May I ask where I can directly download the "ace2004" data? What is the structure of a complete data folder? Can you provide a download link for the dataset? Thank you!

**Comment by laquabe** [comment]
Hi, since OneNet is a multi-step pipeline, some steps may be time-consuming. Therefore, we also provide some intermediate results (e.g. summaries, filtered entities), please visit this link, which can also be found in README.md:
https://drive.google.com/file/d/1rHX7HgWdkwnSPf6p68FHf8_s_6OBrGRK/view
