### ISSUE TITLE
AttributeError: 'PreTrainedTokenizerFast' object has no attribute 'apply_chat_template'

### ISSUE THREAD

**Issue by fanzz1208** [laquabe/OneNet#3]
I downloaded an Nvidia/Llama3-ChatQA-1.5-8B model from Huggingface and encountered an error when running the code. What version of Llama model should I download? My GPU is RTX4090.

You need to determine which candidate entity is more likely to be the mention. Please refer to the above example, give your reasons,
and finally answer serial number of the entity and the name of the entity. If all candidate entities are not appropriate, you can ans
wer '-1.None'.
73it [00:00, 6463.81it/s]
________________________________ Traceback (most recent call last) _________________________________
_ /workspace/OneNet/new_code/prompt.py:277 in <module>                                             _
_                                                                                                  _
_   274 _   _   _   _   _   {"role": "system", "content":system_prompt},                           _
_   275 _   _   _   _   _   {"role": "user", "content": prompt},                                   _
_   276 _   _   _   _   ]                                                                          _
_ _ 277 _   _   _   _   response = llm_call(messages, model_name, pipeline=pipeline)               _
_   278 _   _   _   _   print('-'*50 + 'Response' + '-'*50)                                        _
_   279 _   _   _   _   print(response)                                                            _
_   280 _   _   _   _   line[output_key] = response                                                _
_                                                                                                  _
_ /workspace/OneNet/new_code/LLM_calls.py:62 in llm_call                                           _
_                                                                                                  _
_    59 _   _   response = response.strip()                                                        _
_    60 _   _   return response                                                                    _
_    61 _   elif model_name == 'Llama':                                                            _
_ _  62 _   _   prompt = pipeline.tokenizer.apply_chat_template(messages, tokenize=False, add_ge   _
_    63 _   _   terminators = [pipeline.tokenizer.eos_token_id, pipeline.tokenizer.convert_token   _
_    64 _   _   if do_sample:                                                                      _
_    65 _   _   _   outputs = pipeline(prompt, max_new_tokens=max_new_tokens, eos_token_id=termi   _
____________________________________________________________________________________________________
AttributeError: 'PreTrainedTokenizerFast' object has no attribute 'apply_chat_template'

**Comment by laquabe** [comment]
Hi, for Llama3, we use Meta-Llama-3-8B-Instruct (https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct).
Maybe you can also check the version of transformers, we use the transformers==4.40.0.
