### ISSUE TITLE
where "summary.json"    summary	     summary.json	Get summary of enitities

### ISSUE THREAD

**Issue by fanzz1208** [laquabe/OneNet#5]
“export CUDA_VISIBLE_DEVICES=3
python new_code/prompt.py \
    --dataset_name ace2004 \
    --dataset_path datasets/ace2004/ace2004_test.jsonl \
    --model_name Llama \
    --model_path /workspace/Llama3-ChatQA-1.5-8B/ \
    --func_name summary \
    --exp_name  test \
    --test”
    
    Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "new_code/prompt.py", line 249, in <module>
    prompt = summary_prompt(line)
  File "new_code/prompt.py", line 50, in summary_prompt
    src_dict['title'], src_dict['title'], src_dict['text'])
KeyError: 'title'

    
![image](https://github.com/user-attachments/assets/9ba9af84-082f-4b7c-ad7d-65cad370db90)

**Comment by laquabe** [comment]
Hi, for the summary of entities, you can find them in the _pointwise_raw.jsonl_, which is shown as:
`
{
...
'cand_text': (the original description of entities),
'cand_summary': (the summary of description),
...
}
`
We put it inside _pointwise_raw.jsonl_ as you do not have to racall the initial candidate set. But if you're interested in knowledge base and initial candidate set recall, you can visit NER4EL: https://github.com/Babelscape/ner4el/tree/master.
Then formalize the data as _summary.json_ in zeshel/process_data.

**Comment by laquabe** [comment]
Here is the wiki-based summary: https://drive.google.com/file/d/1ZWZ3BS9KtdpDjfqa1aovtMKtCtyBUs7Y/view?usp=sharing
However, the keys in the dict are different, here is an example:
`
{ "wiki_id": (wiki_id)
"src":{
"text": (the original descriptions of entity),
"summary": (the summary of description),
...
}
}
`
So before you use it, you need to process it to the form of _zeshel/process_data/summary.json_
